service: membership-api

package:
  individually: true
  patterns:
    - "!.git/**"
    - "!.gitignore"
    - "!README.md"
    - "!*.md"

custom:
  env: ${lower(${opt:stage, self:provider.stage})}
  vpcSettings:
    prod:
      securityGroupIds:
        - sg-052314a1eec2f2567
      subnetIds:
        - subnet-01a6b61d749d10c46
    current: ${self:custom.vpcSettings.${self:custom.env}, self:custom.vpcSettings.prod}

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 1024
  timeout: 10
  region: us-east-2
  iam:
    role: arn:aws:iam::428019619026:role/ChurchAppsRole
  environment:
    APP_ENV: ${self:custom.env}

functions:
  api:
    name: membership-api-${sls:stage}-api
    handler: lambda.universal
    events:
      - http:
          path: /{proxy+}
          method: ANY
      - http:
          path: /
          method: ANY
    vpc: ${self:custom.vpcSettings.current}
    package:
      patterns:
        - "!package-lock.json"
        - "!tsconfig.json"
        - "!src/**"
        - "!tools/**"
        - "!*.md"
        - "!DeployProd.bat"
        - "!DeployStaging.bat"
        - "!Dockerfile"
        - "!.git/**"
        - "!.gitignore"
        - "!README.md"

plugins:
  - serverless-plugin-utils
