service: membership-api

package:
  individually: true
  exclude:
    - node_modules/**

custom:
  env: ${lower(${opt:stage, self:provider.stage})}
  vpcSettings:
    prod:
      securityGroupIds:
        - sg-052314a1eec2f2567
      subnetIds:
        - subnet-01a6b61d749d10c46
    staging: {}
    current: ${self:custom.vpcSettings.${self:custom.env}, self:custom.vpcSettings.staging}

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 1024
  timeout: 10
  region: us-east-2
  iam:
    role: arn:aws:iam::428019619026:role/ChurchAppsRole
  environment:
    APP_ENV: ${self:custom.env}

layers:
  dependencies:
    path: layer
    name: ${self:service}-${sls:stage}-dependencies
    description: Dependencies for ${self:service}
    compatibleRuntimes:
      - nodejs18.x

functions:
  api:
    name: membership-api-${sls:stage}-api
    handler: lambda.universal
    events:
      - http:
          path: /{proxy+}
          method: ANY
      - http:
          path: /
          method: ANY
    vpc: ${self:custom.vpcSettings.current}
    layers:
      - {Ref: DependenciesLambdaLayer}
    package:
      patterns:
        - '!node_modules/**'
        - '!package-lock.json'

plugins:
  - serverless-plugin-utils