service: membership-api

package:
  individually: true
  patterns:
    - "!.git/**"
    - "!.gitignore"
    - "!README.md"
    - "!*.md"

custom:
  env: ${lower(${opt:stage, self:provider.stage})}
  vpcSettings:
    prod:
      securityGroupIds:
        - sg-052314a1eec2f2567
      subnetIds:
        - subnet-01a6b61d749d10c46
    current: ${self:custom.vpcSettings.${self:custom.env}, self:custom.vpcSettings.prod}

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 512 # Reduced from 1024MB for cost optimization
  timeout: 10
  region: us-east-2
  iam:
    role: arn:aws:iam::428019619026:role/ChurchAppsRole
  environment:
    APP_ENV: ${self:custom.env}
  logs:
    httpApi:
      logRetentionInDays: 1
  apiGateway:
    throttle:
      rateLimit: 5 # 5 requests per second per IP
      burstLimit: 20 # Allow bursts up to 20 requests per second

layers:
  nodeDependencies:
    path: layer
    name: membership-api-${sls:stage}-node-dependencies
    description: Node.js dependencies for membership-api
    compatibleRuntimes:
      - nodejs20.x
    retain: false

functions:
  api:
    name: membership-api-${sls:stage}-api
    handler: lambda.universal
    layers:
      - { Ref: NodeDependenciesLambdaLayer }
    events:
      - http:
          path: /{proxy+}
          method: ANY
      - http:
          path: /
          method: ANY
    vpc: ${self:custom.vpcSettings.current}
    package:
      patterns:
        - "!package-lock.json"
        - "!tsconfig.json"
        - "!src/**"
        - "!tools/**"
        - "!*.md"
        - "!DeployProd.bat"
        - "!DeployStaging.bat"
        - "!Dockerfile"
        - "!.git/**"
        - "!.gitignore"
        - "!README.md"
        - "!node_modules/**"

plugins:
  - serverless-plugin-utils
