service: membership-api

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 1024
  timeout: 10
  region: us-east-2
  iam:
    role: arn:aws:iam::428019619026:role/ChurchAppsRole
  environment:
    APP_ENV: ${lower(${opt:stage, self:provider.stage})}

functions:
  api:
    handler: lambda.universal
    events:
      - http: ANY {proxy+}
      - http: ANY /

plugins:
  - serverless-layers
  - serverless-plugin-utils

custom:
  serverless-layers:
    dependenciesPath: ./package.json
    layersDeploymentBucket: "lcs-layers"
