service: membership-api

provider:
 name: aws
 runtime: nodejs12.x
 memorySize: 512
 timeout: 10
 region: us-east-2


functions:
 api:
   handler: lambda.universal
   events:
     - http: ANY {proxy+}
     - http: ANY /

plugins:
  - serverless-layers
  
custom:
  serverless-layers:
    dependenciesPath: ./package.json
    layersDeploymentBucket: "lcs-layers"